name: Continuous Delivery
on:
  pull_request:
    branches:
      - main

jobs:
  continuous-delivery:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2

      - name: Build image_thumbnail lambda layer
        run: |
          cd lambda_layer/image_thumbnail
          mkdir -p python
          pip3 install \
            --platform manylinux2014_x86_64 \
            --target=python \
            --implementation cp \
            --python-version 3.9 \
            --only-binary=:all: \
            --upgrade \
            --requirement requirements.txt

      - name: Build image_api lambda layer
        run: |
          cd lambda_layer/image_api
          mkdir -p python
          pip3 install \
            --platform manylinux2014_x86_64 \
            --target=python \
            --implementation cp \
            --python-version 3.9 \
            --only-binary=:all: \
            --upgrade \
            --requirement requirements.txt
